### PR TITLE
move from bower to npm for flickity dep

### PR DESCRIPTION
**Pull request by briangonzalez**

### CODE REVIEW

**Comment by dylanfoster** [comment]
Looks like the tests are failing on node v4

**Comment by briangonzalez** [comment]
@dylanfoster The current active node LTS is 6.0 – mind if I remove node 4?

**Comment by dylanfoster** [comment]
👍 might as well bump the node engine in package.json as well (probably 6.11 is best)

**Comment by briangonzalez** [comment]
@dylanfoster do you know where ember-try's node versions are declared?

**Comment by dylanfoster** [comment]
https://github.com/travelbank/ember-flickity/blob/develop/.travis.yml#L3-L6

**Comment by briangonzalez** [comment]
@dylanfoster done :)

**Comment by briangonzalez** [comment]
@dylanfoster we're looking good now :)

**Pull request merged**
